---
title: "fog_preprocessing"
author: "Chase Fensore"
date: "2023-10-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in fallreports_2023-9-21_train.csv
```{r}
library(caret)
library(data.table)
library(dplyr)
library(sets)
library(scales)
library(tidyr)
library(stringr)
library(tableone)
library(kableExtra) # install.packages("kableExtra")
library(knitr)
library(stringr)

```


```{r}
train_data <- read.csv("train_feats.csv") #("fallreports_2023-9-21_train.csv")
test_data <- read.csv("test_feats.csv") #("fallreports_2023-9-21_test.csv")
```

# Binarize demo: train
```{r}
#
train_data <- train_data %>%
  mutate(Male = if_else(gender == "Male", 1, 0))
train_data <- train_data %>%
  mutate(Female = if_else(gender == "Female", 1, 0))

train_data <- train_data %>%
  mutate(White = if_else(race == "White", 1, 0))
train_data <- train_data %>%
  mutate(Black = if_else(race == "African American/Black", 1, 0))
train_data <- train_data %>%
  mutate(Other_race = if_else(race == "More Than One Race", 1, 0))


# previous_falls
train_data <- train_data %>%
  mutate(faller = if_else(previous_falls == "faller", 1, 0))


# Clinical data:
train_data <- train_data %>%
  mutate(num_falls = if_else(num_falls_6_mo == "None", 0, 
                             if_else(num_falls_6_mo == "1", 1, 
                                     if_else(num_falls_6_mo == "2", 2, 3))))

```

# Binarize demo: TEST
```{r}
test_data <- test_data %>%
  mutate(Male = if_else(gender == "Male", 1, 0))
test_data <- test_data %>%
  mutate(Female = if_else(gender == "Female", 1, 0))

test_data <- test_data %>%
  mutate(White = if_else(race == "White", 1, 0))
test_data <- test_data %>%
  mutate(Black = if_else(race == "African American/Black", 1, 0))
test_data <- test_data %>%
  mutate(Other_race = if_else(race == "More Than One Race", 1, 0))

# previous_falls
test_data <- test_data %>%
  mutate(faller = if_else(previous_falls == "faller", 1, 0))



# Clinical data:
test_data <- test_data %>%
  mutate(num_falls = if_else(num_falls_6_mo == "None", 0, 
                             if_else(num_falls_6_mo == "1", 1, 
                                     if_else(num_falls_6_mo == "2", 2, 3))))
```

# Write binarized train, test to output files:
```{r}
write.csv(train_data, file="./train_feats.csv", row.names=FALSE) # OLD: 9-20-total_feats.csv
write.csv(test_data, file="./test_feats.csv", row.names=FALSE) # OLD: 9-20-total_feats.csv

# For create_folds helper
source('./data_cleaners.R')

# For cross validation
endpoints <- c("fog_q_class")
train_folds <- create_folds(as.data.frame(train_data), endpoints)
write.csv(train_folds, file="./train_folds.csv", row.names = FALSE)
```

# Check nans
```{r}


nan_rows <- test_data[grepl('nan', test_data$tfidf_train, ignore.case = TRUE), ]


```

# Table 1: 
```{r}
# First, join train+test, then de-duplicate on record_id
# Join
tb_all <- rbind(train_data, test_data)

# Determine if a patient had ANY FoG instances: create column "any_FOG"
tb_all <- tb_all %>%
  group_by(record_id) %>%
  mutate(any_FOG = as.integer(any(fog_q_class == 1))) %>%
  ungroup()

# Then, De-dup based on "record_id"
tb_all <- tb_all[!duplicated((tb_all$record_id)),]



# Rename columns
# colnames(tb_all)[colnames(tb_all) == "fog_yn"] = "FoG"
colnames(tb_all)[colnames(tb_all) == "age_at_enrollment"] = "Age, Baseline"
colnames(tb_all)[colnames(tb_all) == "gender"] = "Gender"
colnames(tb_all)[colnames(tb_all) == "race"] = "Race"
colnames(tb_all)[colnames(tb_all) == "ethnicity"] = "Ethnicity"
colnames(tb_all)[colnames(tb_all) == "pd_duration"] = "PD Duration"
colnames(tb_all)[colnames(tb_all) == "num_falls"] = "# Falls, 6 mo."
colnames(tb_all)[colnames(tb_all) == "mds_updrs_iii_binary"] = "MDS UPDRS Stage"
colnames(tb_all)[colnames(tb_all) == "fall_total"] = "Fall Total"
colnames(tb_all)[colnames(tb_all) == "fall_rate"] = "Fall Rate"
colnames(tb_all)[colnames(tb_all) == "previous_falls"] = "Previous Falls"
colnames(tb_all)[colnames(tb_all) == "education"] = "Education"
# Stratum: 2 cols: Y/N for having ANY FoG throughout the study period.
colnames(tb_all)[colnames(tb_all) == "any_FOG"] = "Any FoG"




# Generate table
myVars <- c("Age, Baseline", "Gender", "Race", "Ethnicity", "Education",
            "MDS UPDRS Stage", "Previous Falls", "PD Duration", "Fall Total")
catVars <- c("Gender", "Race", "Ethnicity", "Education", "MDS UPDRS Stage", "Previous Falls")
tab1 <- CreateTableOne(vars = myVars, strata = "Any FoG", data = tb_all, test=TRUE, smd = TRUE)

# Print table 1
p <- print(tab1, printToggle = FALSE, noSpaces = TRUE)
# p <- p[,1:4] # Remove "test" column.

kable(p, format = "latex", booktabs = TRUE)
```

# Table: Mean length of "fall report" text in WORDS for *each instance* of +FoG (i.e. fog_q_class == 1) 
```{r}

reports_analysis <- train_data # rbind(train_data, test_data)
colnames(reports_analysis)[colnames(reports_analysis) == "fog_q_class"] = "FoG"

# SIMPLE TEXT FEATURES:
# Len: WORDS
# Len: CHARACTERS
#reports_analysis$num_words <- str_count(reports_analysis$fall_description, "\\S+")
#reports_analysis$num_characters <- nchar(reports_analysis$fall_description)


# Generate Table: +FoG vs. -Fog reports of falls:

# Generate table: for train+test combined data.
myVars <- c("char_count", "word_count", "word_density", "punctuation_count", "title_word_count", "upper_case_word_count", "stopword_count",
             "noun_count", "verb_count", "adj_count", "adv_count", "pron_count")

newNames <- c("# Characters", "# Words", "Word Density", "# Punctuation", "# Title Words", "# Upper Case", "# Stop Words",
             "# Nouns", "# Verbs", "# Adjectives", "# Adverbs", "# Pronouns")
# Rename cols: 
colnames(reports_analysis)[match(myVars, colnames(reports_analysis))] <- newNames

tab2 <- CreateTableOne(vars = newNames, strata = "FoG", data = reports_analysis, test=TRUE, smd = TRUE)

# Print table 1
p <- print(tab2, printToggle = FALSE, noSpaces = TRUE)
p <- p[,1:3] # Remove "test" column.

kable(p, format = "html", booktabs = TRUE)


```

